services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - echocart
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  email-worker:
    image: echo_cart_email-worker
    container_name: email-worker
    command: node workers/email.worker.js
    env_file:
      - ./backend/.env
    depends_on:
      - rabbitmq
    networks:
      - echocart

  backend:
    image: echo_cart-backend
    container_name: backend
    networks:
      - echocart
    depends_on:
      - rabbitmq

  frontend:
    image: echo_cart-frontend
    container_name: frontend
    depends_on:
      - backend
    networks:
      - echocart

  admin:
    image: echo_cart-admin
    container_name: admin
    depends_on:
      - backend
    networks:
      - echocart

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
      - admin
    networks:
      - echocart

networks:
  echocart:
    driver: bridge
